### ISSUE TITLE
Broken link in Table page

### ISSUE THREAD

**Issue by nghuuphuoc** [anduintransaction/design#26]
https://anduin.design/table#getkey

The link to React doc is broken.

![link](https://user-images.githubusercontent.com/4226036/57351019-86a69380-718a-11e9-8bbb-f7aa3ea25f37.png)

**Comment by dvkndn** [comment]
ahhhhhhhh it's a line break.. I need to find a way to make it's an error

Anyway the suggested way now should be using ref link, like:

```
[React's reconcilation][rr]

[rr]: https://....
```

to minimum line break at the middle of the url..
